# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tapcommon.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tapcommon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftapcommon.proto\x12\x06taprpc\".\n\x08OutPoint\x12\x0c\n\x04txid\x18\x01 \x01(\x0c\x12\x14\n\x0coutput_index\x18\x02 \x01(\r\"O\n\rAssetOutPoint\x12\x18\n\x10\x61nchor_out_point\x18\x01 \x01(\t\x12\x10\n\x08\x61sset_id\x18\x02 \x01(\x0c\x12\x12\n\nscript_key\x18\x03 \x01(\x0c*@\n\rSortDirection\x12\x17\n\x13SORT_DIRECTION_DESC\x10\x00\x12\x16\n\x12SORT_DIRECTION_ASC\x10\x01\x42\x30Z.github.com/lightninglabs/taproot-assets/taprpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tapcommon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/lightninglabs/taproot-assets/taprpc'
  _globals['_SORTDIRECTION']._serialized_start=156
  _globals['_SORTDIRECTION']._serialized_end=220
  _globals['_OUTPOINT']._serialized_start=27
  _globals['_OUTPOINT']._serialized_end=73
  _globals['_ASSETOUTPOINT']._serialized_start=75
  _globals['_ASSETOUTPOINT']._serialized_end=154
# @@protoc_insertion_point(module_scope)
