chain=elementsregtest
server=1
txindex=1
listen=1
fallbackfee=0.00001
rpcuser=user
rpcpassword=pass
rpcallowip=0.0.0.0/0
validatepegin=1
initialfreecoins=2100000000000000
mainchainrpchost=bitcoind
mainchainrpcport=18443
mainchainrpcuser=local_rpc
mainchainrpcpassword=local_rpc_password

[elementsregtest]
port=7042
anyonecanspendaremine=1
rpcbind=0.0.0.0
rpcport=7041
